create table if not exists public.cyberpunk_messages (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 1 and 30),
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.cyberpunk_messages enable row level security;

create policy "Anyone can read cyberpunk chat"
  on public.cyberpunk_messages
  for select
  to anon
  using (true);

create policy "Anyone can post to cyberpunk chat"
  on public.cyberpunk_messages
  for insert
  to anon
  with check (true);

alter publication supabase_realtime add table public.cyberpunk_messages;
