create table if not exists public.cyberpunk_messages (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 1 and 30),
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.cyberpunk_messages enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on table public.cyberpunk_messages to anon, authenticated;
grant select on table public.cyberpunk_scores to anon, authenticated;
grant select on table public.cyberpunk_monthly_scores to anon, authenticated;

drop policy if exists "Anyone can read cyberpunk chat" on public.cyberpunk_messages;
create policy "Anyone can read cyberpunk chat"
  on public.cyberpunk_messages
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can post to cyberpunk chat" on public.cyberpunk_messages;
create policy "Anyone can post to cyberpunk chat"
  on public.cyberpunk_messages
  for insert
  to anon, authenticated
  with check (true);

create table if not exists public.cyberpunk_scores (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 1 and 30),
  score integer not null check (score >= 0),
  achieved_at timestamptz not null default now()
);

create unique index if not exists cyberpunk_scores_nickname_unique
  on public.cyberpunk_scores (lower(nickname));

alter table public.cyberpunk_scores enable row level security;

drop policy if exists "Anyone can read cyberpunk scores" on public.cyberpunk_scores;
create policy "Anyone can read cyberpunk scores"
  on public.cyberpunk_scores
  for select
  to anon, authenticated
  using (true);

create table if not exists public.cyberpunk_monthly_scores (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 1 and 30),
  score integer not null check (score >= 0),
  score_month date not null,
  achieved_at timestamptz not null default now()
);

create unique index if not exists cyberpunk_monthly_scores_nickname_unique
  on public.cyberpunk_monthly_scores (score_month, lower(nickname));

alter table public.cyberpunk_monthly_scores enable row level security;

drop policy if exists "Anyone can read cyberpunk monthly scores" on public.cyberpunk_monthly_scores;
create policy "Anyone can read cyberpunk monthly scores"
  on public.cyberpunk_monthly_scores
  for select
  to anon, authenticated
  using (true);

create or replace function public.submit_cyberpunk_score(
  player_nickname text,
  player_score integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_nickname text := btrim(player_nickname);
  result_rank integer;
  current_month date := date_trunc('month', now() at time zone 'UTC')::date;
begin
  if char_length(clean_nickname) < 1 or char_length(clean_nickname) > 30 then
    raise exception 'Nickname must contain from 1 to 30 characters';
  end if;
  if player_score is null or player_score < 0 then
    raise exception 'Score must be a positive integer';
  end if;

  insert into public.cyberpunk_scores (nickname, score)
  values (clean_nickname, player_score)
  on conflict ((lower(nickname))) do update
    set nickname = excluded.nickname,
        achieved_at = case
          when excluded.score > cyberpunk_scores.score then now()
          else cyberpunk_scores.achieved_at
        end,
        score = greatest(cyberpunk_scores.score, excluded.score);

  delete from public.cyberpunk_scores
  where id in (
    select id
    from public.cyberpunk_scores
    order by score desc, achieved_at asc, id asc
    offset 20
  );

  -- В начале нового месяца клиент запрашивает уже новую дату, поэтому рейтинг
  -- сразу выглядит пустым. При первой записи старые месяцы удаляются физически.
  delete from public.cyberpunk_monthly_scores
  where score_month < current_month;

  insert into public.cyberpunk_monthly_scores (nickname, score, score_month)
  values (clean_nickname, player_score, current_month)
  on conflict (score_month, (lower(nickname))) do update
    set nickname = excluded.nickname,
        achieved_at = case
          when excluded.score > cyberpunk_monthly_scores.score then now()
          else cyberpunk_monthly_scores.achieved_at
        end,
        score = greatest(cyberpunk_monthly_scores.score, excluded.score);

  delete from public.cyberpunk_monthly_scores
  where id in (
    select id
    from public.cyberpunk_monthly_scores
    where score_month = current_month
    order by score desc, achieved_at asc, id asc
    offset 20
  );

  select ranked.position into result_rank
  from (
    select nickname, row_number() over (
      order by score desc, achieved_at asc, id asc
    )::integer as position
    from public.cyberpunk_scores
  ) as ranked
  where lower(ranked.nickname) = lower(clean_nickname);

  return result_rank;
end;
$$;

revoke all on function public.submit_cyberpunk_score(text, integer) from public;
grant execute on function public.submit_cyberpunk_score(text, integer) to anon, authenticated;

create or replace function public.erase_cyberpunk_identity(
  player_nickname text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_nickname text := btrim(player_nickname);
begin
  if char_length(clean_nickname) < 1 or char_length(clean_nickname) > 30 then
    raise exception 'Nickname must contain from 1 to 30 characters';
  end if;

  delete from public.cyberpunk_scores
  where lower(nickname) = lower(clean_nickname);

  delete from public.cyberpunk_monthly_scores
  where lower(nickname) = lower(clean_nickname);
end;
$$;

revoke all on function public.erase_cyberpunk_identity(text) from public;
grant execute on function public.erase_cyberpunk_identity(text) to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'cyberpunk_messages'
  ) then
    alter publication supabase_realtime add table public.cyberpunk_messages;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'cyberpunk_scores'
  ) then
    alter publication supabase_realtime add table public.cyberpunk_scores;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'cyberpunk_monthly_scores'
  ) then
    alter publication supabase_realtime add table public.cyberpunk_monthly_scores;
  end if;
end
$$;
